<a href="https://colab.research.google.com/github/TaehyunRoh/ML_LAB/blob/master/%EB%B0%91%EB%B0%94%EB%8B%A6%EB%B6%80%ED%84%B0_%EC%8B%9C%EC%9E%91%ED%95%98%EB%8A%94_%EB%94%A5%EB%9F%AC%EB%8B%9D2_ch1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#밑바닦부터 시작하는 딥러닝2

#Chapter1. 신경망 복습

##1.1 수학과 파이썬 복습

###1.1.1 벡터와 행렬


'벡터'와 '행렬'

'벡터' : 크기와 방향을 갖은 양./ 숫자가 일렬로 늘어선 집합./ 1차원 배열
'행렬' : 숫자가 2차원 형태(사각형 형상). / 2차원 배열

In [0]:
import numpy as np

x = np.array([1,2,3])
x.__class__ # 클래스 이름 표시


numpy.ndarray

In [0]:
x.shape # 배열의 형상 원소의 수가 3개이다

(3,)

In [0]:
x.ndim # 차원의 수

1

In [0]:
w = np.array([[1,2,3],[4,5,6]])
w.shape

(2, 3)

In [0]:
w.ndim

2

###1.1.2 행렬의 원소별 연산

In [0]:
w = np.array([[1,2,3],[4,5,6]])
x = np.array([[0,1,2],[3,4,5]])

w + x

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [0]:
w * x #원소들끼리 더하기 곱하기

array([[ 0,  2,  6],
       [12, 20, 30]])

###1.1.3 브로드캐스트
형상이 다른 배열 끼리도 연산 가능

In [0]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [0]:
A * 10

array([[10, 20],
       [30, 40]])

In [0]:
# 또 다른 예

A
B = np.array([10,20])
A*B

#B가 array([[10,20],[10,20]])의 형태로 확장된다. 원소곱

array([[10, 40],
       [30, 80]])

###1.1.4 벡터의 내적과 행렬의 곱
 ***XY*** = x_1*y_1 + x_2*y_2
 
 > 두 벡터가 얼마나 같은 방향을 향하고 있는가를 나타낸다. (벡터의 길이가 같다고 한정할 경우 같은 방향은 1 다른 방향은 -1)

In [0]:
# 벡터의 내적

a = np.array([1,2,3,])
b = np.array([4,5,6])

np.dot(a,b)


32

In [0]:
# 행렬의 곱

A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

np.matmul(A,B)

array([[19, 22],
       [43, 50]])

In [0]:
np.dot(A,B)#행렬의 곱과 내적을 구분하여써서 의도를 명확히 나타내자

array([[19, 22],
       [43, 50]])

In [0]:
#100 numpay exercises 들어가서 연습하는게 이득 문제 100개
#https://github.com/rougier/numpy-100

###1.1.5 행렬 형상 확인
앞행렬의 열 뒷행렬의 행 이 맞는 지 확인

##1.2 신경망의 추론
신경망은 두단계 학습, 추론

###1.2.1 신경망 추론 전체 그림


신경망 = 함수 / 입력값과 출력 값이 있다. 

2차원 입력하여 3차원 데이터를 출력하는 함수를 예로 든다. 

신경망을 구현 하려면?

입력층(input layer) : 뉴런 2개 (input layer 2차원)

출력층(ouput layer) : 뉴런 3개 (output layer 3차원)

은닉층(hidden layer)(중간층) :  적당한 수의 뉴런 배치


각각의 화살표에는 가중치가 존재한다.  그 가중치와 뉴련의 값을 각각 곱해서 그 합(합의 값에 활성화 함수 activation fucntion를 적용한 값이 들어간다. )이 다음 뉴련의 입력으로 쓰인다. 


이떄 각 층에서는 이전 뉴련의 값에 영향을 받지 않은'정수'도 더해집니다. (편향 bias)

완전 연결계층 (fully connected layer) : 인접하는 층의 모든 뉴런과 연결

가중치 층으로 판단 -> 2층 신경망




h_1 = x1w_11 + x2w_21 + b_1 (은닉층의 뉴런 _h_1)


**h = xW + b**

In [0]:
import numpy as np
W1 = np.random.randn(2,4)

In [0]:
W1 #가중치는 다 다른다 2층 신경망에서 한개의 층의 히든 레이어  값 구하기 위한 weight

array([[-0.21355538, -0.9688169 ,  2.41526195,  1.81895448],
       [ 0.61757328, -2.44681389,  0.10091314, -2.02956008]])

In [0]:
b1 = np.random.randn(4)
b1

array([-1.50016918,  1.15078323, -0.47470299,  0.15461951])

In [0]:
x = np.random.randn(1, 2) #2차원 데이터 1개 책에서는 한개로 했지만 이해를 돕기위해 그림과 같은 1개의 데이터로함 
x

x1 = np.random.randn(10, 2) #2차원 데이터 10개  
x1

array([[ 0.97322649, -0.41395682],
       [ 1.44552255, -0.68370721],
       [-0.8087068 ,  0.15559594],
       [ 0.3581772 ,  0.80951728],
       [ 0.12421409, -1.13420535],
       [-0.22193562,  0.00880719],
       [ 0.37439205, -0.19520097],
       [ 0.23085916,  0.91427914],
       [ 0.27037778, -0.69285508],
       [ 0.05516052,  0.36644174]])

In [0]:
h = np.matmul(x, W1) + b1
h #히든 레이어의 뉴런에 들어가는 값?활성화 함수를 적용시키지 않았따. 

array([[-2.45033475,  4.03055605,  0.56447883,  3.82179302]])

In [0]:
h1 = np.matmul(x1, W1) + b1
h1 #히든 레이어의 뉴런에 들어가는 값?활성화 함수를 적용시키지 않았따. 

array([[-1.96365561,  1.22078025,  1.83412024,  2.76502443],
       [-2.2311076 ,  1.42324085,  2.94761758,  4.17158408],
       [-1.2313736 ,  1.55355772, -2.41224007, -1.63217266],
       [-1.07672361, -1.176963  ,  0.4720797 , -0.83683642],
       [-2.22715069,  3.80563192, -0.28914965,  2.6824972 ],
       [-1.44733455,  1.34424866, -1.0098469 , -0.266946  ],
       [-1.70067352,  1.26568632,  0.40985354,  1.2317937 ],
       [-0.98483603, -1.30994792,  0.17514513, -1.28104264],
       [-1.9857986 ,  2.5841241 ,  0.108412  ,  2.05261541],
       [-1.28564438,  0.20072805, -0.30449711, -0.48876155]])

10개의 샘플 데이터를 각각 완전 연결계층으로 변화 시켰다. 

완전연결계층에 의한 변환은 '선형'변환이다.'비선형'으로 바꾸기 위해  '활성화 함수' 사용

**시그모이드sigmoid function** 사용

sigma(x) = 1/(1+ exp(-x))

0에서 1사이의 값 반환

In [0]:
def sigmod(x) :
  return 1 / (1 + np.exp(-x))

In [0]:
#시그모이드 함수를 하용하여 은닉층 뉴런을 반환
a = sigmod(h1)
a

array([[0.12307197, 0.77220083, 0.86225183, 0.94075629],
       [0.09699159, 0.80584598, 0.95015077, 0.9848066 ],
       [0.2259411 , 0.82542698, 0.08224408, 0.16353295],
       [0.25412654, 0.2355987 , 0.61587588, 0.30220149],
       [0.0973387 , 0.97823894, 0.42821206, 0.93598591],
       [0.19041212, 0.79318776, 0.26700981, 0.433657  ],
       [0.15437732, 0.78000342, 0.60105276, 0.77413236],
       [0.27193326, 0.21249556, 0.54367469, 0.21737279],
       [0.12070206, 0.92983282, 0.52707649, 0.88621162],
       [0.21659096, 0.55001419, 0.4244585 , 0.38018536]])

In [0]:
#시그모이드 함수에 의해 비선형 변환 가능

In [0]:
import numpy as np
def sigmoid(x) :
  return 1/ (1 + np.exp(-x))

x = np.random.randn(10,2) #입력데이터 10개
W1 = np.random.randn(2,4) #가중치 2*4 은닉층 뉴련수 4개로 만들꺼다 
b1 = np.random.randn(4)
W2 = np.random.randn(4,3) # 마지막 아웃풋은 3차원 데이터로 만들꺼니까 3
b2 = np.random.randn(3)


h = np.matmul(x,W1) + b1
a = sigmoid(h)
s = np.matmul(a,W2) + b2
s

array([[-0.11439386,  0.98758984, -0.58968346],
       [ 0.4736304 ,  0.5125263 ,  1.11704602],
       [ 0.34361374,  1.36307046,  0.00318536],
       [ 0.56690607,  1.1094685 ,  0.97396722],
       [ 0.57337753,  0.91472717,  1.10205998],
       [ 0.41365193,  1.56835991,  0.52505918],
       [ 0.30745533,  0.43303932,  0.81147138],
       [ 0.52033794,  0.93036598,  0.84605544],
       [ 0.4750207 ,  0.18352806,  1.56253737],
       [ 0.55286193,  1.22940587,  0.83001148]])

In [0]:
#각 차원의 값을 이용하여 3 클래스 분류를 할 수 있다. 
# 이 경우 출력된 3차원 벡터의 각 차원은 각 클래스에 대응하는 score가 된다. 
# 출력층 중 가장 큰 값을 내뱉는 뉴런에 해당하는 클래스가 예측 결과가 된다. 

#점수가 높을수록 클래스의 확률도 높아짐 점수를 soft max 함수를 사용하면 확률값이 된다. 

###1.2.2 계층으로 클래스화 및 순전파 구현

In [0]:
# 신경망에서 하는 처리를 꼐층(layer)로 구현
# 완전연결계층에 의한 변환을 Affine 계층으로, 시그모이드 함수에 대한 변환을 sigmoid 계층으로 구현

# 각 계층을 파이썬 클래스로 구현!
# 기본 변환을 수행하는 메서드의 이름 = forward()로 지정.

In [0]:
# 순전파(forward propagation) : 신경망 추론 과정에서 하는 처리 : 입력층에서 출력층으로 향하는 전파
# 역전파(backward propagation) : 신경망 학습 : 순전파와는 반대 방향으로 전파

In [0]:
# 모든 예제의 구현 규칙

# forward()와 backward() 메서드를 갖는다. 
# 모든 계층은 인스턴스 변수인 params와 grads를 가진다. (params, grads??)

# params : 가중치와 편향 같은 매개변수를 담는 리스트
# grads : params에 저장된 각 매개변수에 대응하여, 해당 매개변수의 기울기를 보관하는 리스트

In [0]:
import numpy as np
class Sigmoid :
  def __init__(self):
    self.params = []
  
  def forward(self, x) :
    return 1 / ( 1 + np.exp(-x))
   

In [0]:
class Affine :
  def __init__(self, W, b) :
    self.params = [W,b]
    
  def forward(self, x):
    W,b = self.params
    out = np.matmul(x,W) + b
    return out

In [0]:
#afffine 계층은 초기화 될 떄 가중치와 편향을 받는다. 즉 가중치와 편향은 Affine계층의 매개변수이다. 
#리스트인 params 인스턴스 변수에 보관한다. 



##구현해볼 신경망의 계층 구성

#X -> Affine -> sigmoid -> affine -> S

#점수인 S 출력

In [0]:
# 이 신경망을 Two LayerNet 이라는 클래스로 추상화 하고 주 처리는 predict(x)메서드로 구현

In [0]:
class TwoLayerNet :
  def __init__(self, input_size, hidden_size, output_size) :
    I, H, O = input_size, hidden_size, output_size
    
    
    # 가중치와 편향 초기화
    
    W1 = np.random.randn(I, H)
    b1 = np.random.randn(H)
    W2 = np.random.randn(H,O)
    b2 = np.random.randn(O)
    
    
    # 계층 생성
    
    self.layers = [
        Affine(W1,b1),
        Sigmoid(),
        Affine(W2,b2)
    ]
    
    
    # 모든 가중치를 리스트에 모은다. 
    self.params = []
    for layer in self.layers:
      self.params += layer.params
      
      
  def predict(self, x):
      for layer in self.layers:
        x = layer.forward(x)
      return x

In [0]:
x = np.random.randn(10,2)
model = TwoLayerNet(2,4,3)
s = model.predict(x)

In [0]:
s

array([[-1.23635172,  0.71239252,  2.63763079],
       [-1.32314235,  0.38993969,  2.39595402],
       [-2.12027128, -0.13497624,  1.92271454],
       [-0.84843691, -0.83401541,  1.64932968],
       [-1.39623663,  0.07310946,  2.16856299],
       [-2.38494384, -0.03519767,  1.95307795],
       [-0.77953971,  0.57197411,  2.62295919],
       [-2.22286814, -0.36901296,  1.75465838],
       [-1.26835815,  0.81648638,  2.70828924],
       [-0.75258036, -0.23294516,  2.05821432]])

##1.3 신경망의 학습

In [0]:
# 신경망의 학습은 최적의 매개 변수 값을 찾는 작업이다. (가중치와 편향)

###1.3.1 손실 함수

In [0]:
#학습이 얼마나 잘 되고 잇는지 알기 위한 척도가 필요하다.

#척도 -> 손실(loss) -> 학습 단계의 특정 시점에서 신경망의 성능을 나타내는 척도
#loss는 학습데이터(정답데이터)와 신경망이 예측한 결과를 비교하여 예측이 얼마나 나븐가를 산출한 단일값(스칼라값)

#손실함수(loss function)를 사용

#multi-class classification은 손실함수로 Cross Entropy Error(교차 엔트로피 오차) -> 각 클래스의 확률과 정답 레이블을 이용해 구할 수 있다. 

#